### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by MOJOliciousFTW** [Ehrensverd/weather_db_project_netatmo_tibber#1]
nice work! suggest to make a new table with device_id and some other informative columns. Each weather station (maybe every module?), tibber pulse, yr data, etc, then given a unique device_id. Then, make a table for hourly values with columns device_id, timestamptz and data (maybe not the best, but smash all data in here as a json?). And finally, another table for the not so hourly values e.g. "secondly" values. What do yo think?

**Comment by Ehrensverd** [comment]
Having a table connecting all the date makes sense. I was actually thinking about adding hourly, weekly and monthly tables. Will implement this for sure.
